using ProfitabilityCalculator.Contracts;

namespace ProfitabilityCalculator.Services.ProfitabilityCalculation;

public interface IProfitabilityCalculationService
{
    ProfitabilityCalculationResponse CalculateProfitability(Models.ProfitabilityCalculation profitabilityCalculation);
}